export const RouteName = Object.freeze({
  HOME: 'index',
  PRODUCTS: 'products',
  PRODUCT_DETAIL: 'products-id',
  ABOUT: 'about',
  CONTACT: 'contact',
  ADMIN_LOGIN: 'admin-login',
  ADMIN_DASHBOARD: 'admin',
  ADMIN_PRODUCTS: 'admin-products',
  ADMIN_PRODUCT_CREATE: 'admin-products-create',
  ADMIN_PRODUCT_EDIT: 'admin-products-id-edit',
  ADMIN_CATEGORIES: 'admin-categories',
  ADMIN_MATERIALS: 'admin-materials',
  ADMIN_INVENTORY: 'admin-inventory',
  ADMIN_SALES: 'admin-sales',
  ADMIN_CUSTOMERS: 'admin-customers',
  ADMIN_EXPENSES: 'admin-expenses',
  ADMIN_BANNERS: 'admin-banners',
  ADMIN_REPORTS: 'admin-reports',
  ADMIN_SETTINGS: 'admin-settings',
})
