export const PageTitles = Object.freeze({
  HOME: 'Thash Attire — Premium Women\'s Fashion',
  PRODUCTS: 'Shop Collection',
  PRODUCT_DETAIL: 'Product Details',
  ABOUT: 'About Us',
  CONTACT: 'Contact Us',
  ADMIN_LOGIN: 'Admin Login',
  ADMIN_DASHBOARD: 'Dashboard',
  ADMIN_PRODUCTS: 'Products',
  ADMIN_PRODUCT_CREATE: 'Add Product',
  ADMIN_PRODUCT_DETAIL: 'Product Details',
  ADMIN_PRODUCT_EDIT: 'Edit Product',
  ADMIN_CATEGORIES: 'Categories',
  ADMIN_MATERIALS: 'Materials',
  ADMIN_COMMON_MATERIALS: 'Common Materials',
  ADMIN_MATERIAL_PURCHASES: 'Material Purchases',
  ADMIN_MATERIAL_DETAIL: 'Material Details',
  ADMIN_INVENTORY: 'Inventory',
  ADMIN_ORDERS: 'Orders',
  ADMIN_ORDER_CREATE: 'Create Order',
  ADMIN_ORDER_DETAIL: 'Order Details',
  ADMIN_CUSTOMERS: 'Customers',
  ADMIN_CUSTOMER_DETAIL: 'Customer Details',
  ADMIN_EXPENSES: 'Expenses',
  ADMIN_BANNERS: 'Banners',
  ADMIN_REPORTS: 'Reports',
  ADMIN_SETTINGS: 'Settings',
})
