export const PageTitles = Object.freeze({
  HOME: 'Thash Attire — Premium Women\'s Fashion',
  PRODUCTS: 'Shop Collection',
  PRODUCT_DETAIL: 'Product Details',
  ABOUT: 'About Us',
  CONTACT: 'Contact Us',
  ADMIN_LOGIN: 'Admin Login',
  ADMIN_DASHBOARD: 'Dashboard',
  ADMIN_PRODUCTS: 'Products',
  ADMIN_CATEGORIES: 'Categories',
  ADMIN_MATERIALS: 'Materials',
  ADMIN_INVENTORY: 'Inventory',
  ADMIN_SALES: 'Sales',
  ADMIN_CUSTOMERS: 'Customers',
  ADMIN_EXPENSES: 'Expenses',
  ADMIN_BANNERS: 'Banners',
  ADMIN_REPORTS: 'Reports',
  ADMIN_SETTINGS: 'Settings',
})
