export const Routes = Object.freeze({
  HOME: '/',
  PRODUCTS: '/products',
  PRODUCT_DETAIL: (id) => `/products/${id}`,
  ABOUT: '/about',
  CONTACT: '/contact',
  ADMIN_LOGIN: '/admin/login',
  ADMIN_DASHBOARD: '/admin',
  ADMIN_PRODUCTS: '/admin/products',
  ADMIN_PRODUCT_CREATE: '/admin/products/create',
  ADMIN_PRODUCT_DETAIL: (id) => `/admin/products/${id}`,
  ADMIN_PRODUCT_EDIT: (id) => `/admin/products/${id}/edit`,
  ADMIN_MATERIAL_DETAIL: (id) => `/admin/materials/${id}`,
  ADMIN_CATEGORIES: '/admin/categories',
  ADMIN_MATERIALS: '/admin/materials',
  ADMIN_MATERIAL_PURCHASES: '/admin/materials/purchases',
  ADMIN_COMMON_MATERIALS: '/admin/materials/common',
  ADMIN_INVENTORY: '/admin/inventory',
  ADMIN_ORDERS: '/admin/orders',
  ADMIN_ORDER_CREATE: '/admin/orders/create',
  ADMIN_ORDER_DETAIL: (id) => `/admin/orders/${id}`,
  ADMIN_CUSTOMERS: '/admin/customers',
  ADMIN_CUSTOMER_DETAIL: (id) => `/admin/customers/${id}`,
  ADMIN_EXPENSES: '/admin/expenses',
  ADMIN_BANNERS: '/admin/banners',
  ADMIN_REPORTS: '/admin/reports',
  ADMIN_SETTINGS: '/admin/settings',
  ADMIN_OFFERS: '/admin/offers',
  ADMIN_OFFER_CREATE: '/admin/offers/create',
  ADMIN_OFFER_EDIT: (id) => `/admin/offers/${id}/edit`,
})

